CREATE TABLE users
(
    id    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(50)                                            NOT NULL,
    email VARCHAR(50)
);

CREATE TABLE items
(
    id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(50)                                            NOT NULL,
    description  VARCHAR(250),
    is_available boolean,
    owner_id     INTEGER REFERENCES users (id),
    request_id   INTEGER REFERENCES request (id)
);

CREATE TABLE booking
(
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    item_id    INTEGER REFERENCES items (id),
    booker_id  INTEGER REFERENCES users (id),
    status     VARCHAR(50)
);

CREATE TABLE request
(
    id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(250),
    requestor_id INTEGER REFERENCES users (id)
);

CREATE TABLE comments
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(250),
    item_id INTEGER REFERENCES items(id),
    author_id INTEGER REFERENCES users(id)
);